# Generated by Django 4.2.11 on 2024-05-07 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0004_alter_todoitem_title_alter_todolist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('todolist', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('user', 'title')},
        ),
    ]
